# Generated by Django 4.0.1 on 2022-01-15 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='contenido',
            field=models.TextField(max_length=250),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='portada',
            field=models.ImageField(upload_to='portadas/articulos'),
        ),
    ]
