# Generated by Django 4.0.1 on 2022-02-10 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_articulo_contenido_alter_articulo_portada'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='token',
            field=models.CharField(max_length=14, null=True, unique=True),
        ),
    ]
