# Generated by Django 4.0.1 on 2022-02-10 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_usuario_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='token',
            field=models.CharField(blank=True, max_length=24, null=True, unique=True),
        ),
    ]
