# Generated by Django 4.0.1 on 2022-02-10 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_usuario_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='profile_picture',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='fotos/perfiles'),
        ),
    ]
