# Generated by Django 4.0.1 on 2022-02-11 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_articulo_categoria_alter_articulo_contenido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='contenido',
            field=models.TextField(),
        ),
    ]
